//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class dishes
    {
        public int id_dishes { get; set; }
        public System.DateTime date_dish { get; set; }
        public Nullable<int> count_dish { get; set; }
        public Nullable<int> id_empl { get; set; }
        public Nullable<int> id_menu { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual menu menu { get; set; }
    }
}
