//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restEntities : DbContext
    {
        public restEntities()
            : base("name=restEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<position> position { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<order11> order11Set { get; set; }
        public virtual DbSet<dishes> dishes { get; set; }
    }
}
