//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class order11
    {
        public int id_position { get; set; }
        public Nullable<int> id_menu { get; set; }
        public Nullable<System.DateTime> data_order1 { get; set; }
        public Nullable<int> table_n { get; set; }
    
        public virtual menu menu { get; set; }
    }
}
