//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rest
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public string product { get; set; }
        public int quantity { get; set; }
        public string unit { get; set; }
        public System.DateTime date_sup { get; set; }
        public Nullable<int> id_empl { get; set; }
        public Nullable<double> summ { get; set; }
        public int id_prod { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
